python3 -m main --input_subscription "projects/task-cf-370710/subscriptions/cf-pub_sub-subscription" --output_table "task-cf-370710.task_df_dataset.table-dataflow" --output_error_table "task-cf-370710.task_df_dataset.table-dataflow-error" --project "task-cf-370710" --region=US --template_location "gs://task-cf-370710-dataflow-bucket/template/dataflow-job" --staging_location "gs://task-cf-370710-dataflow-bucket/tmp" --temp_location "gs://task-cf-370710-dataflow-bucket/tmp" --runner=DataflowRunner --setup_file='setup.py' --autoscaling_algorithm=NONE



python3 -m main --input_subscription "projects/task-cf-370710/subscriptions/cf-pub_sub-subscription" --output_table "task-cf-370710.task_df_dataset.table-dataflow" --output_error_table "task-cf-370710.task_df_dataset.table-dataflow-error" --project "task-cf-370710" --template_location "gs://task-cf-370710-dataflow-bucket/template/dataflow-job" --staging_location "gs://task-cf-370710-dataflow-bucket/tmp" --temp_location "gs://task-cf-370710-dataflow-bucket/tmp"